// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://brqhjgidcyvfqtgxiomw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJycWhqZ2lkY3l2ZnF0Z3hpb213Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0MDgzMjcsImV4cCI6MjA2NDk4NDMyN30.Xdb5e0VsV5PD810SlG-7CvDe8smBM09XxfHyYFpwV_g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);